import * as satellite from 'satellite.js';
import { SatelliteData } from '../types/satellites';
import { loadSatelliteCoverage } from './coverageService';
import { fetchSatcatStatusMap, type SatcatStatusMap } from './satcatService';
import { getStatusCategory } from '../utils/satelliteStatus';
import { log } from '../utils/logger';

// ─── TLE Cache Configuration ─────────────────────────────────────────────────
// TTL of 30 minutes: fresh enough for accurate SGP4 propagation, lenient enough
// to avoid CelesTrak rate-limits during development (multiple hot-reloads).
const TLE_CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes

const CELESTRAK_API = {
  EUTELSAT: 'https://celestrak.org/NORAD/elements/gp.php?NAME=EUTELSAT&FORMAT=tle',
  ONEWEB: 'https://celestrak.org/NORAD/elements/gp.php?NAME=ONEWEB&FORMAT=tle'
};

// Prebuilt static file generated by scripts/update-celestrak.js.
// It contains both filtered EUTELSAT and ONEWEB TLEs.
const CELESTRAK_FILE = {
  EUTELSAT: '/celestrak.txt',
  ONEWEB: '/celestrak.txt',
};

const CACHE_KEYS = {
  EUTELSAT_TLE: 'tle_eutelsat_data',
  EUTELSAT_TS: 'tle_eutelsat_ts',
  ONEWEB_TLE: 'tle_oneweb_data',
  ONEWEB_TS: 'tle_oneweb_ts',
};

type CoverageManifest = Record<string, boolean>;

const EUTELSAT_COVERAGE_FILE_BY_ALIAS: Record<string, string> = {
  E115WB: '40425',
  E117WA: '39122',
  E117WB: '41589',
  E139WA: '28187',
  E16A: '32487',
  E172B: '42432',
  E174A: '28924',
  E21B: '38652',
  E33F: '43216',
  E36D: '44333',
  E53A: '39021',
  E5WB: '40882',
  E65WA: '41389',
  E70B: '40985',
  E7B: '41036',
  E7C: '43215',
  E7WA: '36101',
  E8WB: '41550',
  E9B: '41954',
  HB13F: '54048',
  HB13G: '55842',
  KONNECT: '44914',
};

let coverageManifestPromise: Promise<Set<string>> | null = null;
const FORCE_LOCAL_CELESTRAK = String(import.meta.env.VITE_FORCE_LOCAL_CELESTRAK ?? '').toLowerCase() === 'true';

// ─── localStorage TLE Cache Helpers ──────────────────────────────────────────

function isCacheValid(tsKey: string): boolean {
  try {
    const ts = localStorage.getItem(tsKey);
    if (!ts) return false;
    return Date.now() - parseInt(ts, 10) < TLE_CACHE_TTL_MS;
  } catch {
    return false;
  }
}

/**
 * Remove localStorage TLE entries that have outlived their TTL.
 * Called once at module load so stale megabyte-sized TLE strings do not
 * linger in localStorage across page loads when they would be re-fetched
 * anyway on next use.
 */
function clearStaleTLECache(): void {
  const pairs = [
    { dataKey: CACHE_KEYS.EUTELSAT_TLE, tsKey: CACHE_KEYS.EUTELSAT_TS },
    { dataKey: CACHE_KEYS.ONEWEB_TLE,   tsKey: CACHE_KEYS.ONEWEB_TS   },
  ];
  try {
    for (const { dataKey, tsKey } of pairs) {
      if (!isCacheValid(tsKey)) {
        localStorage.removeItem(dataKey);
        localStorage.removeItem(tsKey);
      }
    }
  } catch {
    // localStorage unavailable — no-op
  }
}
clearStaleTLECache();

function readFromCache(dataKey: string): string | null {
  try {
    return localStorage.getItem(dataKey);
  } catch {
    return null;
  }
}

function writeToCache(dataKey: string, tsKey: string, data: string): void {
  try {
    localStorage.setItem(dataKey, data);
    localStorage.setItem(tsKey, String(Date.now()));
  } catch (e) {
    // If localStorage is full/unavailable, silently skip
    console.warn('[TLE Cache] Failed to write to localStorage:', e);
  }
}

async function loadCoverageManifest(): Promise<Set<string>> {
  if (coverageManifestPromise) {
    return coverageManifestPromise;
  }

  coverageManifestPromise = fetch('/coverage/coverageManifest.json')
    .then(async (response) => {
      if (!response.ok) {
        return new Set<string>();
      }

      const manifest = await response.json() as CoverageManifest;
      return new Set(
        Object.entries(manifest)
          .filter(([, available]) => available)
          .map(([satelliteId]) => satelliteId)
      );
    })
    .catch((error) => {
      console.warn('[Coverage Manifest] Failed to load manifest:', error);
      return new Set<string>();
    });

  return coverageManifestPromise;
}

async function fetchBundledTLE(operator: 'EUTELSAT' | 'ONEWEB'): Promise<string> {
  const filePath = CELESTRAK_FILE[operator];
  if (!filePath) return '';

  const fileResp = await fetch(filePath);
  if (!fileResp.ok) {
    throw new Error(`Bundled TLE file unavailable for ${operator}: HTTP ${fileResp.status}`);
  }
  return await fileResp.text();
}

/**
 * Fetch TLE data for a given operator with cache-first strategy:
 *   1. Return localStorage entry if < TTL_MS old.
 *   2. Try CelesTrak live API; if successful, update cache.
 *   3. If API fails but stale cache exists, use stale cache (better than nothing).
 *   4. Last resort: fall back to bundled static file.
 */
async function fetchTLE(
  operator: 'EUTELSAT' | 'ONEWEB',
  dataKey: string,
  tsKey: string
): Promise<string> {
  if (FORCE_LOCAL_CELESTRAK) {
    try {
      log(`[TLE] VITE_FORCE_LOCAL_CELESTRAK=true -> serving ${operator} TLEs from bundled static file.`);
      return await fetchBundledTLE(operator);
    } catch (fileError) {
      console.warn(`[TLE] Bundled static file failed for ${operator}:`, fileError);
      const stale = readFromCache(dataKey);
      if (stale) {
        console.warn(`[TLE] Falling back to cached ${operator} TLEs because bundled static file is unavailable.`);
        return stale;
      }
      return '';
    }
  }

  // 1. Cache hit (fresh)
  if (isCacheValid(tsKey)) {
    const cached = readFromCache(dataKey);
    if (cached) {
      log(`[TLE Cache] Serving fresh ${operator} TLEs from localStorage.`);
      return cached;
    }
  }

  // 2. Try live API
  try {
    log(`[TLE Cache] Fetching fresh ${operator} TLEs from CelesTrak…`);
    const resp = await fetch(CELESTRAK_API[operator]);
    if (resp.ok) {
      const text = await resp.text();
      if (text.trim().length > 100) { // Sanity check: not an error page
        writeToCache(dataKey, tsKey, text);
        return text;
      }
    }
    throw new Error(`Bad response from CelesTrak: ${resp.status}`);
  } catch (apiError) {
    console.warn(`[TLE Cache] CelesTrak API failed for ${operator}:`, apiError);

    // 3. Stale cache fallback
    const stale = readFromCache(dataKey);
    if (stale) {
      console.warn(`[TLE Cache] Using stale ${operator} TLEs from localStorage (age > ${TLE_CACHE_TTL_MS / 60000} min).`);
      return stale;
    }

    // 4. Last resort: bundled static file (only if one exists for this operator)
    console.warn(`[TLE Cache] Falling back to bundled static file for ${operator}.`);
    return await fetchBundledTLE(operator);
  }
}

// ─── TLE Parsing ─────────────────────────────────────────────────────────────

export interface SatRecSatellite {
  satrec: any;
  name: string;
  noradId: string;
}

function parseTLE(tleData: string, operator: string) {
  const lines = tleData.split('\n').filter(line => line.trim());
  const satellites = [];

  for (let i = 0; i < lines.length; i += 3) {
    if (i + 2 >= lines.length) break;

    const name = lines[i].trim();
    const line1 = lines[i + 1];
    const line2 = lines[i + 2];

    const satrec = satellite.twoline2satrec(line1, line2);
    if (satrec && name.includes(operator)) {
      satellites.push({
        name,
        satrec,
        noradId: line1.substring(2, 7).trim()
      });
    }
  }
  return satellites;
}

const getEutelsatCoverageAlias = (satelliteName: string): string | null => {
  const normalizedName = satelliteName.trim().toUpperCase();

  if (normalizedName === 'EUTELSAT KONNECT VHTS') return 'KVHTS';
  if (normalizedName === 'EUTELSAT KONNECT') return 'KONNECT';

  const hotbirdMatch = normalizedName.match(/^EUTELSAT HOTBIRD (\d+)([A-Z])$/);
  if (hotbirdMatch) {
    return `HB${hotbirdMatch[1]}${hotbirdMatch[2]}`;
  }

  const westMatch = normalizedName.match(/^EUTELSAT (\d+) WEST ([A-Z])$/);
  if (westMatch) {
    return `E${westMatch[1]}W${westMatch[2]}`;
  }

  const directMatch = normalizedName.match(/^EUTELSAT (\d+)([A-Z])$/);
  if (directMatch) {
    return `E${directMatch[1]}${directMatch[2]}`;
  }

  return null;
};

export const resolveCoverageFileId = (
  sat: { name: string; noradId: string },
  coverageManifest: Set<string>
): string | null => {
  if (coverageManifest.has(sat.noradId)) {
    return sat.noradId;
  }

  const alias = getEutelsatCoverageAlias(sat.name);
  if (!alias) {
    return null;
  }

  const mappedFileId = EUTELSAT_COVERAGE_FILE_BY_ALIAS[alias];
  if (mappedFileId && coverageManifest.has(mappedFileId)) {
    return mappedFileId;
  }

  return null;
};

// ─── Position Calculation ─────────────────────────────────────────────────────

export function calculatePosition(sat: any, date: Date = new Date()) {
  const positionAndVelocity = satellite.propagate(sat.satrec, date);
  const gmst = satellite.gstime(date);

  if (positionAndVelocity && positionAndVelocity.position && typeof positionAndVelocity.position !== 'boolean') {
    const geoPosition = satellite.eciToGeodetic(positionAndVelocity.position, gmst);
    return {
      lat: satellite.degreesLat(geoPosition.latitude),
      lng: satellite.degreesLong(geoPosition.longitude),
      alt: geoPosition.height
    };
  }

  return { lat: 0, lng: 0, alt: 0 };
}

function attachSatelliteId<T extends { type: string; features: any[] }>(
  coverageData: T | null,
  satelliteName: string
): T | null {
  if (!coverageData) return null;

  return {
    ...coverageData,
    features: coverageData.features.map((feature) => ({
      ...feature,
      properties: {
        ...(feature.properties ?? {}),
        satelliteId: satelliteName,
      },
    })),
  };
}

// ─── Main Fetch Entry Point ───────────────────────────────────────────────────

/**
 * Build a single SatelliteData entry, resolving its operational status from the
 * SATCAT map and skipping decayed satellites.
 *
 * Returns null when the satellite's SATCAT entry is marked as decayed (code 'D'
 * or non-null DECAY date) — the caller must filter these out.
 */
function buildSatelliteData(
  sat: { name: string; satrec: any; noradId: string },
  type: 'EUTELSAT' | 'ONEWEB',
  orbitType: 'GEO' | 'LEO',
  coverageData: ReturnType<typeof attachSatelliteId>,
  satcatMap: SatcatStatusMap | null,
  capacity: SatelliteData['capacity'],
  coverageIndexSuffix: string
): SatelliteData | null {
  // When satcatMap is null the SATCAT endpoint was completely unavailable.
  // The TLE sources already filter for active constellations, so defaulting to
  // 'operational' is more correct than rendering everything as unknown/gray.
  let opsStatus;
  if (satcatMap === null) {
    opsStatus = 'operational' as const;
  } else {
    // SATCAT is available: look up the satellite's status code.
    // undefined → satellite not found in SATCAT → 'unknown' (dark gray)
    const rawCode = satcatMap.get(sat.noradId);
    opsStatus = getStatusCategory(rawCode);
  }

  // Decayed satellites must not appear in the scene at all
  if (opsStatus === 'decayed') return null;

  return {
    id: sat.noradId,
    name: sat.name,
    noradId: sat.noradId,
    type,
    orbitType,
    opsStatus,
    satrec: sat.satrec,
    position: calculatePosition(sat),
    referenced_coverages: coverageData || { type: 'FeatureCollection' as const, features: [] },
    coverages: coverageData
      ? coverageData.features.map((feature, index) => ({
          name: `${sat.name}_${coverageIndexSuffix}_${index + 1}`,
          feature,
        }))
      : [{ name: sat.name, feature: { type: 'Feature' as const, properties: {}, geometry: null as any } }],
    capacity,
  };
}

export async function fetchSatellites(): Promise<SatelliteData[]> {
  try {
    // Fetch TLE data and SATCAT status map in parallel — SATCAT is independent
    // of TLE data and both requests hit different CelesTrak endpoints.
    const [eutelsatTLE, onewebTLE, satcatMap, coverageManifest] = await Promise.all([
      fetchTLE('EUTELSAT', CACHE_KEYS.EUTELSAT_TLE, CACHE_KEYS.EUTELSAT_TS),
      fetchTLE('ONEWEB',   CACHE_KEYS.ONEWEB_TLE,   CACHE_KEYS.ONEWEB_TS),
      fetchSatcatStatusMap(),
      loadCoverageManifest(),
    ]);

    const eutelsatSats = parseTLE(eutelsatTLE, 'EUTELSAT');
    const onewebSats   = parseTLE(onewebTLE,   'ONEWEB');

    log(`[fetchSatellites] ${eutelsatSats.length} EUTELSAT + ${onewebSats.length} ONEWEB satellites parsed.`);

    const eutelsatSatPromises = eutelsatSats.map(async (sat) => {
      const coverageFileId = resolveCoverageFileId(sat, coverageManifest);
      if (coverageFileId && coverageFileId !== sat.noradId) {
        log(`[Coverage] Using mapped GEO coverage file ${coverageFileId}.json for ${sat.name} (${sat.noradId}).`);
      }

      const coverageData = coverageFileId
        ? attachSatelliteId(
            await loadSatelliteCoverage(coverageFileId, sat.name, 'EUTELSAT', 10),
            sat.name
          )
        : null;
      return buildSatelliteData(
        sat, 'EUTELSAT', 'GEO', coverageData, satcatMap,
        { maxThroughput: 100, bandwidth: { ku: 500, ka: 300, c: 200 }, availability: 0.99 },
        'beam'
      );
    });

    const onewebSatPromises = onewebSats.map(async (sat) => {
      const coverageData = coverageManifest.has(sat.noradId)
        ? attachSatelliteId(
            await loadSatelliteCoverage(sat.noradId, sat.name, 'ONEWEB', 600),
            sat.name
          )
        : null;
      return buildSatelliteData(
        sat, 'ONEWEB', 'LEO', coverageData, satcatMap,
        {
          // Source: EOPortal OneWeb mission profile — "capacity per satellite: 7.2 Gbps"
          maxThroughput: 7.2,
          bandwidth: {
            // 8 frequency channels × 250 MHz per channel = 2 GHz total Ku-band spectrum.
            // Frequency reuse: 4-cell pattern (LHCP/RHCP isolation), 2 beams share each channel.
            // The 7.2 Gbps headline capacity already accounts for this reuse — do NOT multiply
            // per-channel capacity by 16 beams; the correct multiplier is 8 channels.
            ku: 250, // MHz — per Ku-band channel (user links)
            ka: 150, // MHz — Ka-band gateway/feeder links
            // No C-band: OneWeb Gen 1 is strictly Ku (user) + Ka (gateway)
          },
          availability: 0.99,
          // Source: EOPortal — 7.2 Gbps total per satellite (16 beams × ~450 Mbps/beam).
          officialAggregateCapacityGbps: 7.2,
          // Single-user simulation estimate at boresight, clear sky, full health.
          // This is NOT 7200/16 — it represents what one terminal at beam center receives,
          // not the total shared beam capacity. Max observed terminal speed: ~150 Mbps.
          simulatedEffectiveBeamCapacityMbps: 200,
        },
        'zone'
      );
    });

    const rawResults = [
      ...await Promise.all(eutelsatSatPromises),
      ...await Promise.all(onewebSatPromises),
    ];

    // Remove nulls (decayed satellites that must not appear in the scene)
    const satellites = rawResults.filter((s): s is SatelliteData => s !== null);

    const decayedCount = rawResults.length - satellites.length;
    log(
      `[fetchSatellites] ${satellites.length} satellites loaded ` +
      `(${decayedCount} decayed entries suppressed).`
    );

    return satellites;
  } catch (error) {
    console.error('Error fetching satellite data:', error);
    return [];
  }
}
