import * as satellite from 'satellite.js';
import { SatelliteData } from '../types/satellites';
import { loadSatelliteCoverage } from './coverageService';
import { fetchSatcatStatusMap, type SatcatStatusMap } from './satcatService';
import { getStatusCategory } from '../utils/satelliteStatus';
import { log } from '../utils/logger';

// ─── TLE Cache Configuration ─────────────────────────────────────────────────
// TTL of 30 minutes: fresh enough for accurate SGP4 propagation, lenient enough
// to avoid CelesTrak rate-limits during development (multiple hot-reloads).
const TLE_CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes

const CELESTRAK_API = {
  EUTELSAT: 'https://celestrak.org/NORAD/elements/gp.php?NAME=EUTELSAT&FORMAT=tle',
  ONEWEB: 'https://celestrak.org/NORAD/elements/gp.php?NAME=ONEWEB&FORMAT=tle'
};

/**
 * How long the live CelesTrak call may take before the fallbacks take over.
 *
 * ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
 * `fetchTLE` has a careful four-step ladder — fresh cache, live API, stale
 * cache, bundled static file — and without a deadline the ladder is unreachable
 * below step 2. A filtered guest network does not refuse the connection, it
 * SWALLOWS it: the promise stays pending, so the boot screen holds on
 * "Loading satellite data and coverage…" indefinitely and the perfectly good
 * bundled `celestrak.txt` two steps below is never consulted. Measured during
 * the 2026-08-27 review: the application never finished booting at all.
 *
 * Five seconds is well beyond a healthy CelesTrak response and well inside the
 * patience of someone opening a demo in front of a customer. Timing out is not
 * a failure mode here — it is the trigger that reaches data we already ship.
 */
export const CELESTRAK_FETCH_TIMEOUT_MS = 5_000;

/**
 * `fetch` with a deadline, degrading safely where `AbortSignal.timeout` is
 * missing rather than dropping the request on the floor.
 */
export function fetchWithTimeout(url: string, timeoutMs: number): Promise<Response> {
  if (typeof AbortSignal !== 'undefined' && typeof AbortSignal.timeout === 'function') {
    return fetch(url, { signal: AbortSignal.timeout(timeoutMs) });
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  return fetch(url, { signal: controller.signal }).finally(() => clearTimeout(timer));
}

// Prebuilt static file generated by scripts/update-celestrak.js.
// It contains both filtered EUTELSAT and ONEWEB TLEs.
const CELESTRAK_FILE = {
  EUTELSAT: '/celestrak.txt',
  ONEWEB: '/celestrak.txt',
};

const CACHE_KEYS = {
  EUTELSAT: 'tle_eutelsat',
  ONEWEB: 'tle_oneweb',
};

type CoverageManifest = Record<string, boolean>;

const EUTELSAT_COVERAGE_FILE_BY_ALIAS: Record<string, string> = {
  E115WB: '40425',
  E117WA: '39122',
  E117WB: '41589',
  E139WA: '28187',
  E16A: '37836',
  E172B: '42741',
  E174A: '28924',
  E21B: '38992',
  E28E: '39285',
  E28F: '38778',
  E28G: '40364',
  E33F: '29270',
  E36C: '41191',
  E36D: '59346',
  E3B: '39773',
  E53A: '40277',
  E5WB: '44624',
  E65WA: '41382',
  E70B: '39020',
  E7B: '39163',
  E7C: '44334',
  E7WA: '37816',
  E8WB: '40875',
  E9B: '41310',
  E10B: '54259',
  HB13F: '54048',
  HB13G: '54225',
  KONNECT: '45027',
  KVHTS: '53765',
};

const EUTELSAT_ALIAS_BY_COVERAGE_FILE_ID: Record<string, string> = Object.fromEntries(
  Object.entries(EUTELSAT_COVERAGE_FILE_BY_ALIAS).map(([alias, fileId]) => [fileId, alias])
);

let coverageManifestPromise: Promise<Set<string>> | null = null;
const FORCE_LOCAL_CELESTRAK = String(import.meta.env.VITE_FORCE_LOCAL_CELESTRAK ?? '').toLowerCase() === 'true';

// ─── IndexedDB + CompressionStream TLE Cache ─────────────────────────────────
// A raw TLE file is ~500 KB. After gzip it drops to ~80 KB. IndexedDB has no
// practical quota at this scale, unlike localStorage's 5 MB budget which two
// raw TLE strings would consume entirely.
// CompressionStream / DecompressionStream are native browser APIs (no deps),
// available in Chrome 80+, Firefox 113+, Safari 16.4+.

interface TLECacheEntry {
  data: Uint8Array;   // gzip-compressed TLE text
  timestamp: number;  // Date.now() at write time
}

let _dbPromise: Promise<IDBDatabase> | null = null;

function openTLECacheDB(): Promise<IDBDatabase> {
  if (_dbPromise) return _dbPromise;
  _dbPromise = new Promise<IDBDatabase>((resolve, reject) => {
    const req = indexedDB.open('tleCache', 1);
    req.onupgradeneeded = () => { req.result.createObjectStore('entries'); };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => { _dbPromise = null; reject(req.error); };
  });
  return _dbPromise;
}

async function compressTLE(text: string): Promise<Uint8Array> {
  const cs = new CompressionStream('gzip');
  const writer = cs.writable.getWriter();
  writer.write(new TextEncoder().encode(text));
  writer.close();
  const chunks: Uint8Array[] = [];
  const reader = cs.readable.getReader();
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }
  const out = new Uint8Array(chunks.reduce((n, c) => n + c.length, 0));
  let offset = 0;
  for (const c of chunks) { out.set(c, offset); offset += c.length; }
  return out;
}

async function decompressTLE(data: Uint8Array): Promise<string> {
  const ds = new DecompressionStream('gzip');
  const writer = ds.writable.getWriter();
  writer.write(new Uint8Array(data).buffer);
  writer.close();
  const chunks: Uint8Array[] = [];
  const reader = ds.readable.getReader();
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }
  const out = new Uint8Array(chunks.reduce((n, c) => n + c.length, 0));
  let offset = 0;
  for (const c of chunks) { out.set(c, offset); offset += c.length; }
  return new TextDecoder().decode(out);
}

async function isCacheValid(key: string): Promise<boolean> {
  try {
    const db = await openTLECacheDB();
    const entry = await new Promise<TLECacheEntry | undefined>((resolve, reject) => {
      const req = db.transaction('entries', 'readonly').objectStore('entries').get(key);
      req.onsuccess = () => resolve(req.result as TLECacheEntry | undefined);
      req.onerror = () => reject(req.error);
    });
    return !!entry && (Date.now() - entry.timestamp) < TLE_CACHE_TTL_MS;
  } catch {
    return false;
  }
}

// Reads regardless of TTL — used for the stale-cache fallback path.
async function readFromCache(key: string): Promise<string | null> {
  try {
    const db = await openTLECacheDB();
    const entry = await new Promise<TLECacheEntry | undefined>((resolve, reject) => {
      const req = db.transaction('entries', 'readonly').objectStore('entries').get(key);
      req.onsuccess = () => resolve(req.result as TLECacheEntry | undefined);
      req.onerror = () => reject(req.error);
    });
    if (!entry) return null;
    return await decompressTLE(entry.data);
  } catch {
    return null;
  }
}

// Fire-and-forget — caller does not need to await the write to return TLE text.
async function writeToCache(key: string, data: string): Promise<void> {
  try {
    const [db, compressed] = await Promise.all([openTLECacheDB(), compressTLE(data)]);
    await new Promise<void>((resolve, reject) => {
      const tx = db.transaction('entries', 'readwrite');
      tx.objectStore('entries').put({ data: compressed, timestamp: Date.now() } as TLECacheEntry, key);
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
    });
  } catch (e) {
    console.warn('[TLE Cache] Failed to write to IndexedDB:', e);
  }
}

// Best-effort cleanup of expired entries. Runs once at module load.
// Also purges the old localStorage keys left over from before this migration.
async function clearStaleTLECache(): Promise<void> {
  // Remove legacy localStorage entries (one-time migration).
  try {
    ['tle_eutelsat_data', 'tle_eutelsat_ts', 'tle_oneweb_data', 'tle_oneweb_ts'].forEach(
      (k) => localStorage.removeItem(k)
    );
  } catch { /* localStorage unavailable */ }

  try {
    const db = await openTLECacheDB();
    for (const key of Object.values(CACHE_KEYS)) {
      const entry = await new Promise<TLECacheEntry | undefined>((resolve, reject) => {
        const req = db.transaction('entries', 'readonly').objectStore('entries').get(key);
        req.onsuccess = () => resolve(req.result as TLECacheEntry | undefined);
        req.onerror = () => reject(req.error);
      });
      if (entry && (Date.now() - entry.timestamp) >= TLE_CACHE_TTL_MS) {
        await new Promise<void>((resolve, reject) => {
          const tx = db.transaction('entries', 'readwrite');
          tx.objectStore('entries').delete(key);
          tx.oncomplete = () => resolve();
          tx.onerror = () => reject(tx.error);
        });
      }
    }
  } catch { /* IndexedDB unavailable — no-op */ }
}
void clearStaleTLECache();

async function loadCoverageManifest(): Promise<Set<string>> {
  if (coverageManifestPromise) {
    return coverageManifestPromise;
  }

  coverageManifestPromise = fetch('/coverage/coverageManifest.json')
    .then(async (response) => {
      if (!response.ok) {
        return new Set<string>();
      }

      const manifest = await response.json() as CoverageManifest;
      return new Set(
        Object.entries(manifest)
          .filter(([, available]) => available)
          .map(([satelliteId]) => satelliteId)
      );
    })
    .catch((error) => {
      console.warn('[Coverage Manifest] Failed to load manifest:', error);
      return new Set<string>();
    });

  return coverageManifestPromise;
}

async function fetchBundledTLE(operator: 'EUTELSAT' | 'ONEWEB'): Promise<string> {
  const filePath = CELESTRAK_FILE[operator];
  if (!filePath) return '';

  const fileResp = await fetch(filePath);
  if (!fileResp.ok) {
    throw new Error(`Bundled TLE file unavailable for ${operator}: HTTP ${fileResp.status}`);
  }
  return await fileResp.text();
}

/**
 * Fetch TLE data for a given operator with cache-first strategy:
 *   1. Return IndexedDB entry if < TTL_MS old.
 *   2. Try CelesTrak live API; if successful, update cache (async, non-blocking).
 *   3. If API fails but stale cache exists, use stale cache (better than nothing).
 *   4. Last resort: fall back to bundled static file.
 *
 * Exported, with `timeoutMs` injectable, so the regression test can drive the
 * real ladder against a genuinely never-settling `fetch` in milliseconds rather
 * than in the five seconds production waits. Production callers pass nothing and
 * get `CELESTRAK_FETCH_TIMEOUT_MS`; there is no test-only branch in the code
 * under test.
 */
/**
 * The newest TLE epoch in a catalogue, ms, or `null` if it holds none.
 *
 * Reads the epoch field of line 1 (columns 19–32: two-digit year, then day of
 * year with fraction) rather than building a satrec: this runs on the fallback
 * path, where the point is to choose a file quickly, not to propagate it.
 */
export function newestTleEpochMs(text: string): number | null {
  let newest: number | null = null;
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trimEnd();
    if (!line.startsWith('1 ') || line.length < 32) continue;
    const twoDigitYear = Number(line.slice(18, 20));
    const dayOfYear = Number(line.slice(20, 32));
    if (!Number.isFinite(twoDigitYear) || !Number.isFinite(dayOfYear)) continue;
    // The TLE two-digit year pivots at 57 — the convention the format itself
    // fixes, not a guess about this catalogue.
    const year = twoDigitYear < 57 ? 2000 + twoDigitYear : 1900 + twoDigitYear;
    const ms = Date.UTC(year, 0, 1) + (dayOfYear - 1) * 86_400_000;
    if (newest === null || ms > newest) newest = ms;
  }
  return newest;
}

/**
 * Choose between the two offline candidates by the age of the DATA, not by a
 * fixed rung order.
 *
 * ── WHY THIS IS NOT SIMPLY "BUNDLED BEFORE STALE CACHE" ─────────────────────
 * The original ladder always preferred the stale cache, which was wrong the day
 * `public/celestrak.txt` was refreshed: on 2026-08-29 the bundled file carried
 * epochs five months newer than a cache entry that was merely past its 30-minute
 * TTL. But the reverse rule is wrong just as often — a cache written by a
 * successful live fetch two hours ago is fresher than a bundled file shipped
 * with a build from last month, and preferring the file would throw away the
 * better data.
 *
 * Neither fixed order is right because rung position is a proxy for freshness,
 * and a bad one. The TLE epochs are the freshness, so they decide. A candidate
 * whose epochs cannot be read loses to one whose can; if neither can be read,
 * the cache wins, because it was at least fetched from CelesTrak at some point.
 */
export function fresherCatalogue(
  staleCache: string | null,
  bundled: string | null,
): { text: string; source: Extract<TleSource, 'cache-stale' | 'bundled'> } | null {
  if (!staleCache) return bundled ? { text: bundled, source: 'bundled' } : null;
  if (!bundled) return { text: staleCache, source: 'cache-stale' };

  const cacheEpoch = newestTleEpochMs(staleCache);
  const bundledEpoch = newestTleEpochMs(bundled);
  if (bundledEpoch !== null && (cacheEpoch === null || bundledEpoch > cacheEpoch)) {
    return { text: bundled, source: 'bundled' };
  }
  return { text: staleCache, source: 'cache-stale' };
}

/**
 * Which rung of the `fetchTLE` ladder actually served the data.
 *
 * ── WHY THIS IS RECORDED ────────────────────────────────────────────────────
 * The ladder degrades silently by design — that is what keeps the application
 * booting on a filtered network — but a caller that PRESENTS the data cannot
 * inherit that silence. REVISIT's TLE comparison publishes numbers measured
 * from this catalogue, and two runs ten minutes apart can legitimately differ
 * (cache expiry, a live fetch replacing the bundled file). Without the rung and
 * the instant, that difference is unexplainable on screen and reads as the tool
 * being unreliable.
 *
 * `'bundled'` in particular must never be described as live: the file ships
 * with the build and can be weeks old.
 */
export type TleSource = 'live' | 'cache-fresh' | 'cache-stale' | 'bundled';

export interface TleProvenance {
  source: TleSource;
  /** When this fetch resolved, ms. NOT the age of the data it returned. */
  retrievedAtMs: number;
}

const tleProvenance = new Map<string, TleProvenance>();

function recordTleProvenance(operator: 'EUTELSAT' | 'ONEWEB', source: TleSource): void {
  tleProvenance.set(operator, { source, retrievedAtMs: Date.now() });
}

/** Provenance of the most recent successful `fetchTLE` for this operator. */
export function getTleProvenance(operator: 'EUTELSAT' | 'ONEWEB'): TleProvenance | null {
  return tleProvenance.get(operator) ?? null;
}

export async function fetchTLE(
  operator: 'EUTELSAT' | 'ONEWEB',
  cacheKey: string,
  timeoutMs: number = CELESTRAK_FETCH_TIMEOUT_MS
): Promise<string> {
  if (FORCE_LOCAL_CELESTRAK) {
    try {
      log(`[TLE] VITE_FORCE_LOCAL_CELESTRAK=true -> serving ${operator} TLEs from bundled static file.`);
      const bundled = await fetchBundledTLE(operator);
      recordTleProvenance(operator, 'bundled');
      return bundled;
    } catch (fileError) {
      console.warn(`[TLE] Bundled static file failed for ${operator}:`, fileError);
      const stale = await readFromCache(cacheKey);
      if (stale) {
        console.warn(`[TLE] Falling back to cached ${operator} TLEs because bundled static file is unavailable.`);
        recordTleProvenance(operator, 'cache-stale');
        return stale;
      }
      return '';
    }
  }

  // 1. Cache hit (fresh)
  if (await isCacheValid(cacheKey)) {
    const cached = await readFromCache(cacheKey);
    if (cached) {
      log(`[TLE Cache] Serving fresh ${operator} TLEs from IndexedDB.`);
      recordTleProvenance(operator, 'cache-fresh');
      return cached;
    }
  }

  // 2. Try live API
  try {
    log(`[TLE Cache] Fetching fresh ${operator} TLEs from CelesTrak…`);
    const resp = await fetchWithTimeout(CELESTRAK_API[operator], timeoutMs);
    if (resp.ok) {
      const text = await resp.text();
      if (text.trim().length > 100) { // Sanity check: not an error page
        void writeToCache(cacheKey, text); // async write — don't block returning TLE text
        recordTleProvenance(operator, 'live');
        return text;
      }
    }
    throw new Error(`Bad response from CelesTrak: ${resp.status}`);
  } catch (apiError) {
    console.warn(`[TLE Cache] CelesTrak API failed for ${operator}:`, apiError);

    // 3. Offline candidates: the stale cache and the bundled file. Both are
    //    gathered before either is chosen, because the choice is made on the
    //    age of their contents rather than on which rung they sit.
    const stale = await readFromCache(cacheKey);
    const bundled = await fetchBundledTLE(operator).catch((fileError) => {
      console.warn(`[TLE] Bundled static file unavailable for ${operator}:`, fileError);
      return null;
    });

    const chosen = fresherCatalogue(stale, bundled);
    if (!chosen) {
      throw apiError;
    }
    const epochMs = newestTleEpochMs(chosen.text);
    const epochNote = epochMs === null ? 'no readable epoch' : new Date(epochMs).toISOString().slice(0, 10);
    console.warn(
      chosen.source === 'cache-stale'
        ? `[TLE Cache] Using stale ${operator} TLEs from IndexedDB (age > ${TLE_CACHE_TTL_MS / 60000} min; newest epoch ${epochNote}).`
        : `[TLE] Using the bundled static file for ${operator} (newest epoch ${epochNote}) — newer than the cached set.`
    );
    recordTleProvenance(operator, chosen.source);
    return chosen.text;
  }
}

// ─── TLE Parsing ─────────────────────────────────────────────────────────────

function parseTLE(tleData: string, operator: string) {
  const lines = tleData.split('\n').filter(line => line.trim());
  const satellites = [];

  for (let i = 0; i < lines.length; i += 3) {
    if (i + 2 >= lines.length) break;

    const name = lines[i].trim();
    const line1 = lines[i + 1];
    const line2 = lines[i + 2];

    const satrec = satellite.twoline2satrec(line1, line2);
    if (satrec && name.includes(operator)) {
      satellites.push({
        name,
        satrec,
        noradId: line1.substring(2, 7).trim()
      });
    }
  }
  return satellites;
}

const getEutelsatCoverageAlias = (satelliteName: string): string | null => {
  const normalizedName = satelliteName.trim().toUpperCase();

  if (normalizedName === 'EUTELSAT KONNECT VHTS') return 'KVHTS';
  if (normalizedName === 'EUTELSAT KONNECT') return 'KONNECT';

  const hotbirdMatch = normalizedName.match(/^EUTELSAT HOTBIRD (\d+)([A-Z])$/);
  if (hotbirdMatch) {
    return `HB${hotbirdMatch[1]}${hotbirdMatch[2]}`;
  }

  const westMatch = normalizedName.match(/^EUTELSAT (\d+) WEST ([A-Z])$/);
  if (westMatch) {
    return `E${westMatch[1]}W${westMatch[2]}`;
  }

  const directMatch = normalizedName.match(/^EUTELSAT (\d+)([A-Z])$/);
  if (directMatch) {
    return `E${directMatch[1]}${directMatch[2]}`;
  }

  return null;
};

export const resolveCoverageFileId = (
  sat: { name: string; noradId: string },
  coverageManifest: Set<string>
): string | null => {
  const alias = getEutelsatCoverageAlias(sat.name);
  const mappedFileId = alias ? EUTELSAT_COVERAGE_FILE_BY_ALIAS[alias] : undefined;

  if (mappedFileId && coverageManifest.has(mappedFileId)) {
    return mappedFileId;
  }

  if (coverageManifest.has(sat.noradId)) {
    const ownerAlias = EUTELSAT_ALIAS_BY_COVERAGE_FILE_ID[sat.noradId];
    if (!ownerAlias || ownerAlias === alias) {
      return sat.noradId;
    }

    console.warn(
      `[Coverage] Refusing suspicious direct GEO coverage match ${sat.noradId}.json for ${sat.name}; `
      + `that file is reserved for alias ${ownerAlias}.`
    );
    return null;
  }

  if (!alias) {
    return null;
  }

  return null;
};

// ─── Position Calculation ─────────────────────────────────────────────────────

/**
 * Propagate a satellite to a given date using SGP4.
 *
 * Returns isPositionValid: false on any propagation failure (bad TLE, decayed orbit,
 * numerical divergence). Do NOT treat a result with lat/lng/alt = 0 as a valid
 * position — (0°N, 0°E) is the Gulf of Guinea, not an error sentinel.
 */
export function calculatePosition(
  sat: any,
  date: Date = new Date()
): { lat: number; lng: number; alt: number; isPositionValid: boolean } {
  if (!sat.satrec) return { lat: 0, lng: 0, alt: 0, isPositionValid: false };

  try {
    const positionAndVelocity = satellite.propagate(sat.satrec, date);
    const gmst = satellite.gstime(date);

    if (positionAndVelocity && positionAndVelocity.position && typeof positionAndVelocity.position !== 'boolean') {
      const geoPosition = satellite.eciToGeodetic(positionAndVelocity.position, gmst);
      const lat = satellite.degreesLat(geoPosition.latitude);
      const lng = satellite.degreesLong(geoPosition.longitude);
      const alt = geoPosition.height;

      // Malformed satrec objects can produce NaN/Infinity from satellite.js without throwing.
      if (!isFinite(lat) || !isFinite(lng) || !isFinite(alt)) {
        return { lat: 0, lng: 0, alt: 0, isPositionValid: false };
      }

      return { lat, lng, alt, isPositionValid: true };
    }
  } catch {
    // Propagation failure (decayed TLE, numerical divergence) — fall through.
  }

  return { lat: 0, lng: 0, alt: 0, isPositionValid: false };
}

function attachSatelliteId<T extends { type: string; features: any[] }>(
  coverageData: T | null,
  satelliteName: string
): T | null {
  if (!coverageData) return null;

  return {
    ...coverageData,
    features: coverageData.features.map((feature) => ({
      ...feature,
      properties: {
        ...(feature.properties ?? {}),
        satelliteId: satelliteName,
      },
    })),
  };
}

// ─── Main Fetch Entry Point ───────────────────────────────────────────────────

/**
 * Build a single SatelliteData entry, resolving its operational status from the
 * SATCAT map and skipping decayed satellites.
 *
 * Returns null when the satellite's SATCAT entry is marked as decayed (code 'D'
 * or non-null DECAY date) — the caller must filter these out.
 */
function buildSatelliteData(
  sat: { name: string; satrec: any; noradId: string },
  type: 'EUTELSAT' | 'ONEWEB',
  orbitType: 'GEO' | 'LEO',
  coverageFileId: string | null,
  coverageData: ReturnType<typeof attachSatelliteId>,
  satcatMap: SatcatStatusMap | null,
  capacity: SatelliteData['capacity'],
  coverageIndexSuffix: string
): SatelliteData | null {
  // When satcatMap is null the SATCAT endpoint was completely unavailable.
  // The TLE sources already filter for active constellations, so defaulting to
  // 'operational' is more correct than rendering everything as unknown/gray.
  let opsStatus;
  if (satcatMap === null) {
    opsStatus = 'operational' as const;
  } else {
    // SATCAT is available: look up the satellite's status code.
    // undefined → satellite not found in SATCAT → 'unknown' (dark gray)
    const rawCode = satcatMap.get(sat.noradId);
    opsStatus = getStatusCategory(rawCode);
  }

  // Decayed satellites must not appear in the scene at all
  if (opsStatus === 'decayed') return null;

  const tleJulianEpoch = Number(sat.satrec?.jdsatepoch);
  const tleEpochMs = Number.isFinite(tleJulianEpoch)
    ? (tleJulianEpoch - 2440587.5) * 86_400_000
    : undefined;

  return {
    id: sat.noradId,
    name: sat.name,
    noradId: sat.noradId,
    coverageFileId,
    type,
    orbitType,
    opsStatus,
    satrec: sat.satrec,
    tleEpochMs,
    position: { ...calculatePosition(sat) },
    referenced_coverages: coverageData || { type: 'FeatureCollection' as const, features: [] },
    coverages: coverageData
      ? coverageData.features.map((feature, index) => ({
          name: `${sat.name}_${coverageIndexSuffix}_${index + 1}`,
          feature,
        }))
      : [{ name: sat.name, feature: { type: 'Feature' as const, properties: {}, geometry: null as any } }],
    capacity,
  };
}

export async function fetchSatellites(): Promise<SatelliteData[]> {
  try {
    // Fetch TLE data and SATCAT status map in parallel — SATCAT is independent
    // of TLE data and both requests hit different CelesTrak endpoints.
    const [eutelsatTLE, onewebTLE, satcatMap, coverageManifest] = await Promise.all([
      fetchTLE('EUTELSAT', CACHE_KEYS.EUTELSAT),
      fetchTLE('ONEWEB',   CACHE_KEYS.ONEWEB),
      fetchSatcatStatusMap(),
      loadCoverageManifest(),
    ]);

    const eutelsatSats = parseTLE(eutelsatTLE, 'EUTELSAT');
    const onewebSats   = parseTLE(onewebTLE,   'ONEWEB');

    log(`[fetchSatellites] ${eutelsatSats.length} EUTELSAT + ${onewebSats.length} ONEWEB satellites parsed.`);

    const eutelsatSatPromises = eutelsatSats.map(async (sat) => {
      const coverageFileId = resolveCoverageFileId(sat, coverageManifest);
      if (coverageFileId && coverageFileId !== sat.noradId) {
        log(`[Coverage] Using mapped GEO coverage file ${coverageFileId}.json for ${sat.name} (${sat.noradId}).`);
      }

      const coverageData = coverageFileId
        ? attachSatelliteId(
            await loadSatelliteCoverage(coverageFileId, sat.name, 'EUTELSAT', 10),
            sat.name
          )
        : null;
      return buildSatelliteData(
        sat, 'EUTELSAT', 'GEO', coverageFileId ?? null, coverageData, satcatMap,
        { maxThroughput: 100, bandwidth: { ku: 500, ka: 300, c: 200 }, availability: 0.99 },
        'beam'
      );
    });

    const onewebSatPromises = onewebSats.map(async (sat) => {
      const coverageData = coverageManifest.has(sat.noradId)
        ? attachSatelliteId(
            await loadSatelliteCoverage(sat.noradId, sat.name, 'ONEWEB', 600),
            sat.name
          )
        : null;
      return buildSatelliteData(
        sat, 'ONEWEB', 'LEO', sat.noradId, coverageData, satcatMap,
        {
          // Source: EOPortal OneWeb mission profile — "capacity per satellite: 7.2 Gbps"
          maxThroughput: 7.2,
          bandwidth: {
            // 8 frequency channels × 250 MHz per channel = 2 GHz total Ku-band spectrum.
            // Frequency reuse: 4-cell pattern (LHCP/RHCP isolation), 2 beams share each channel.
            // The 7.2 Gbps headline capacity already accounts for this reuse — do NOT multiply
            // per-channel capacity by 16 beams; the correct multiplier is 8 channels.
            ku: 250, // MHz — per Ku-band channel (user links)
            ka: 150, // MHz — Ka-band gateway/feeder links
            // No C-band: OneWeb Gen 1 is strictly Ku (user) + Ka (gateway)
          },
          availability: 0.99,
          // Source: EOPortal — 7.2 Gbps total per satellite (16 beams × ~450 Mbps/beam).
          officialAggregateCapacityGbps: 7.2,
          // Single-user simulation estimate at boresight, clear sky, full health.
          // This is NOT 7200/16 — it represents what one terminal at beam center receives,
          // not the total shared beam capacity. Max observed terminal speed: ~150 Mbps.
          simulatedEffectiveBeamCapacityMbps: 200,
        },
        'zone'
      );
    });

    const rawResults = [
      ...await Promise.all(eutelsatSatPromises),
      ...await Promise.all(onewebSatPromises),
    ];

    // Remove nulls (decayed satellites that must not appear in the scene)
    const satellites = rawResults.filter((s): s is SatelliteData => s !== null);

    const decayedCount = rawResults.length - satellites.length;
    log(
      `[fetchSatellites] ${satellites.length} satellites loaded ` +
      `(${decayedCount} decayed entries suppressed).`
    );

    return satellites;
  } catch (error) {
    console.error('Error fetching satellite data:', error);
    return [];
  }
}
